import type { CountyScoreSummary } from "@/generated/models";
import { AtlasMap } from "@/components/atlas-map";
import { RankedCounties } from "@/components/ranked-counties";
import { CountyProfile } from "@/components/county-profile";

export function AtlasDashboard({ geometry, scores, counties, detail, copied, onCopy, selectedFips, selectedState, selectedDistrict, showTable, onSelect, onToggleTable }: { geometry?: GeoJSON.FeatureCollection; scores?: CountyScoreSummary[]; counties?: CountyScoreSummary[]; detail?: import("@/generated/models").CountyDetail; copied: boolean; onCopy: () => void; selectedFips: string; selectedState: string; selectedDistrict: string; showTable: boolean; onSelect: (fips: string) => void; onToggleTable: () => void }) {
  const results = counties ?? [];
  return <div className="dashboard-grid"><article className="card map-card"><div className="card-title-row"><div><span className="eyebrow">County Review Priority</span><h3>Counties suggested for review</h3></div><span className="map-scope">{selectedDistrict !== "ALL" ? `${selectedDistrict} highlighted` : selectedState === "ALL" ? "Included U.S. counties" : `${selectedState} counties highlighted`}</span></div><div className="map-wrap">{geometry && scores ? <AtlasMap geometry={geometry as never} scores={scores} selectedFips={selectedFips} selectedState={selectedState} selectedDistrict={selectedDistrict} onSelect={onSelect} /> : <div className="map-loading">Loading map…</div>}</div><div className="legend" aria-label="Map review priority legend"><span>Lower review priority</span><span className="legend-ramp"><i /><i /><i /><i /><i /><i /></span><span>Higher review priority</span><small>{selectedDistrict !== "ALL" ? "Outlined counties belong to the selected health district." : selectedState === "ALL" ? "Gray counties are outside the included comparison." : `Highlighted counties are in ${selectedState}.`}</small></div></article><div className="dashboard-profile">{detail ? <CountyProfile detail={detail} copied={copied} onCopy={onCopy} /> : <div className="card profile-card"><p>Select a county to see its details.</p></div>}</div><RankedCounties counties={results} selectedFips={selectedFips} showTable={showTable} onSelect={onSelect} onToggleTable={onToggleTable} /></div>;
}
