import type { ScoreSettings } from "@/lib/atlas-ui";

export function ScoringLab({ settings, onChange }: { settings: ScoreSettings; onChange: (settings: ScoreSettings) => void }) {
  return <section className="scoring-section section" id="scoring"><div className="section-heading light-heading"><div><span className="eyebrow light">Transparent assumptions</span><h2>Scoring lab</h2><p>Change the three exposed assumptions. The API recomputes every county using the governed methodology.</p></div></div><div className="scoring-grid"><article className="formula-card"><span className="formula-label">Default formula</span><div className="formula"><span>Human signal weakness</span><b>×</b><span>{settings.ecological_share}% ecological + {100 - settings.ecological_share}% community</span></div><p>Missing county-linked human records remain an explicit assumption and never become zero cases.</p></article><div className="controls-card"><ScoreControl label="Ecological share" value={`${settings.ecological_share}%`} min={40} max={85} step={5} current={settings.ecological_share} note="Balances ecological evidence against community barriers." onChange={(value) => onChange({ ...settings, ecological_share: value })} /><ScoreControl label="Low-incidence breakpoint" value={`${settings.low_incidence_breakpoint} / 100k`} min={5} max={25} current={settings.low_incidence_breakpoint} note="Published incidence at this value has no human-signal weakness." onChange={(value) => onChange({ ...settings, low_incidence_breakpoint: value })} /><ScoreControl label="No county-linked record value" value={String(settings.missing_human_weakness)} min={40} max={90} step={5} current={settings.missing_human_weakness} note="Represents uncertainty from missing publishable county records." onChange={(value) => onChange({ ...settings, missing_human_weakness: value })} /></div></div></section>;
}

function ScoreControl({ label, value, min, max, step = 1, current, note, onChange }: { label: string; value: string; min: number; max: number; step?: number; current: number; note: string; onChange: (value: number) => void }) {
  return <label className="range-control"><div><span>{label}</span><strong>{value}</strong></div><input aria-label={label} type="range" min={min} max={max} step={step} value={current} onChange={(event) => onChange(Number(event.target.value))} /><small>{note}</small></label>;
}
